const Settings = {
	startTurn: -0.25,   // angle of new year's eve
	winding: +1,        // ...
};

/*
const numDays = 365;
const numWeeks = numDays / 7;
const firstWeekLength = ...
const lastWeekLength = ...
const numFullWeeks = ...
*/
